import fs from 'node:fs';
import path from 'node:path';
import {z} from 'zod';
const translit={'ё':'e','ж':'zh','х':'kh','ц':'ts','ч':'ch','ш':'sh','щ':'sch','ю':'yu','я':'ya','й':'y','ы':'y','э':'e','ъ':'','ь':'','а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','з':'z','и':'i','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f'};
const slug=s=>s.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').split('').map(c=>translit[c]??c).join('').replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const file=process.argv[2];if(!file){console.error('Использование: npm run import-cars -- cars.json|cars.csv');process.exit(1)}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(Boolean))rows.push(row);row=[]}else field+=c}row.push(field);if(row.some(Boolean))rows.push(row);const head=rows.shift()?.map(x=>x.trim())||[];return rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]||undefined])))}
const number=z.preprocess(v=>v===''||v===undefined||v===null?null:v,z.coerce.number().finite().nonnegative().nullable());
const schema=z.object({brand:z.string().trim().min(1),model:z.string().trim().min(1),generation:z.string().trim().optional().nullable(),facelift:z.string().trim().optional().nullable(),country:z.string().trim().optional(),class:z.string().trim().optional().nullable(),body:z.string().trim().optional().nullable(),doors:number,seats:number,engine:z.string().trim().optional().nullable(),displacement:number,horsepower:number,torque:number,fuel:z.string().trim().optional().nullable(),transmission:z.string().trim().optional().nullable(),drive:z.string().trim().optional().nullable(),acceleration:number,topSpeed:number,consumption:number,clearance:number,length:number,width:number,height:number,wheelbase:number,weight:number,trunk:number,priceMin:number,priceMax:number,yearStart:number,yearEnd:number,description:z.string().trim().optional().nullable(),pros:z.union([z.array(z.string()),z.string()]).optional(),cons:z.union([z.array(z.string()),z.string()]).optional(),photos:z.union([z.array(z.string()),z.string()]).optional(),tags:z.union([z.array(z.string()),z.string()]).optional()});
const list=v=>Array.isArray(v)?v:v?String(v).split('|').map(s=>s.trim()).filter(Boolean):[];
let rows;try{const text=fs.readFileSync(path.resolve(file),'utf8');rows=file.toLowerCase().endsWith('.csv')?parseCsv(text):JSON.parse(text)}catch(e){console.error('Не удалось прочитать файл:',e.message);process.exit(1)}if(!Array.isArray(rows)){console.error('Ожидается массив записей.');process.exit(1)}
const grouped=new Map(),seen=new Set();let rejected=0,duplicate=0;for(const raw of rows){const parsed=schema.safeParse(raw);if(!parsed.success){rejected++;continue}const v=parsed.data;const brandSlug=slug(v.brand),modelSlug=slug(v.model),generationSlug=v.generation?slug(v.generation):null,id=`${brandSlug}-${modelSlug}${generationSlug?`-${generationSlug}`:''}`;if(seen.has(id)){duplicate++;continue}seen.add(id);const car={id,brand:v.brand,brandSlug,model:v.model,modelSlug,generation:v.generation||null,generationSlug,facelift:v.facelift||null,yearStart:v.yearStart??null,yearEnd:v.yearEnd??null,country:v.country||'Не указана',class:v.class||null,body:v.body||null,doors:v.doors??null,seats:v.seats??null,engine:v.engine||null,displacement:v.displacement??null,horsepower:v.horsepower??null,torque:v.torque??null,fuel:v.fuel||null,transmission:v.transmission||null,drive:v.drive||null,acceleration:v.acceleration??null,topSpeed:v.topSpeed??null,consumption:v.consumption??null,clearance:v.clearance??null,length:v.length??null,width:v.width??null,height:v.height??null,wheelbase:v.wheelbase??null,weight:v.weight??null,trunk:v.trunk??null,priceMin:v.priceMin??null,priceMax:v.priceMax??null,description:v.description||null,pros:list(v.pros),cons:list(v.cons),photos:list(v.photos).filter(p=>p.startsWith('https://')||p.startsWith('/')),tags:list(v.tags),popularity:0};grouped.set(brandSlug,[...(grouped.get(brandSlug)||[]),car])}
const out=path.join(process.cwd(),'data','cars');fs.mkdirSync(out,{recursive:true});for(const [name,cars] of grouped){const target=path.join(out,`${name}.json`),existing=fs.existsSync(target)?JSON.parse(fs.readFileSync(target,'utf8')):[],merged=new Map(existing.map(c=>[c.id,c]));for(const car of cars)merged.set(car.id,car);fs.writeFileSync(target,JSON.stringify([...merged.values()],null,2)+'\n')}
console.log(`Импортировано: ${seen.size}; отклонено: ${rejected}; дубликатов: ${duplicate}; файлов марок: ${grouped.size}`);
